### ISSUE TITLE
Can this get You banned via VAC or Faceit AC / ESEA ?

### ISSUE THREAD

**Issue by Shadoweee77** [403-Fruit/csctl#1]
Can this get You banned via VAC or Faceit AC / ESEA ?
Either way, awesome stuff!

**Comment by 403-Fruit** [comment]
I can say for sure that VAC won’t be an issue because there is no hooking or tampering with the csgo process whatsoever. There is no code signatures or integrity violations for VAC to detect since nothing is injected or modified. This functionality is built-in to the client by Valve and it’s probably safe to assume that they would lock it behind sv_cheats, or insecure mode long before they’d ban people for using it.   

Although I will say that with VACnet, Valve’s new AI anticheat software, anything is possible because it’s essentially a black box, likely even for valve themselves. Basically, in the eyes of a computer that only knows what hackers look like and what you look like, if you walk like a hacker, and kill enemies with precise robotic input like a hacker, then you’re probably a hacker. The reason I’m not too concerned about it is because the mechanism, input, and output of this program is not very similar at all to that of a hacker, unless you **really** tried to find a way to use it like a cheat for some reason. It far more closely resembles the behavior of someone using macros, and I can’t find a single instance of someone being banned for using those. 

Faceit, however, is a different story. From [Faceit’s anti-cheat FAQ](https://support.faceit.com/hc/en-us/articles/115000061290-Anti-Cheat-FAQ?mobile_site=true):  

> **What is deemed to be a cheat?**  
> ...  

> External scripting/macros designed to gain an advantage over other players (e.g. No recoil script, ...)  

There is a 99.99% chance this falls in that category.   

To reiterate, there is some risk to using this software and I can’t promise that it is 100% safe. Only Valve could say for sure because it’s very much a gray area  and they have never confirmed or denied that macros are against the rules. Maybe you could make an issue over on [ValveSoftware/csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux/) for further clarification.

**Comment by Shadoweee77** [comment]
Thanks for responding!
I'm planning on using the tool to change radiomenu file in csgo ui directory. I have a fairly advanced exec system ( You can find it on my github if you'd like to ) for cs:go and just recently thought of using radio menu as a way to navigate / use it as it can execute commands and generates a handy GUI. I want to use something like telnet to be able to send data from the cs:go console to copy radiomenu file from specified folder inside cfg to ui directory via python script. Radiomenu has a limit of 4 menus, that's why it is necessary. 
Best regards, Shadoweee

**Comment by 403-Fruit** [comment]
Nice! You may be interested in the `menuselect` command. It allows you to select radio menu options with a command. For example, in servers with the !guns menu you can make a bind to select a certain weapon like so  

```
alias selectak47 "sm_guns;menuselect 3;menuselect 4;cancelselect"
```  

Where the numbers correspond to the number of the menu item you want to select. `cancelselect` closes the menu. I used this one for a server that had the player model select menu.  

```
alias sel1 "sm_models;menuselect 1;menuselect 1;cancelselect;alias cyclemodels sel2"
alias sel2 "sm_models;menuselect 1;menuselect 2;cancelselect;alias cyclemodels sel3"
alias sel3 "sm_models;menuselect 1;menuselect 3;cancelselect;alias cyclemodels sel4"
alias sel4 "sm_models;menuselect 1;menuselect 4;cancelselect;alias cyclemodels sel1"
alias cyclemodels sel1
bind capslock cyclemodels
```

It selects models 1-4 from the model select menu and allows you to cycle through them really fast.

**Comment by Shadoweee77** [comment]
Awesome stuff, didn't knew about those actually, but I think I will link the commands inside the file so there isn't a confussion. Still thanks so much!
